
-- GENERAR UN INSERT O UPDATE A UNA DB
CREATE PROCEDURE SP_UPSERT_USUARIO (
    X_ID IN OUT NUMBER,
    X_NOMBRE IN VARCHAR2,
    X_FECHA_NACIMIENTO IN DATE
)
AS
    V_ID_AUX PERSONA.ID%TYPE;
BEGIN
    -- PRIMERO BUSCO SI EL ID EXISTE
    SELECT ID
    INTO V_ID_AUX
    FROM PERSONA
    WHERE ID = X_ID;

    -- SI NO EXISTE, LO INSERTAMOS
    IF V_ID_AUX = NULL
    THEN
        INSERT INTO PERSONA VALUES (NOMBRE, FECHA_NACIMIENTO);
    ELSE
        -- SI EXISTE, LO UPDATEAMOS
        UPDATE PERSONA
        SET
            NOMBRE = X_NOMBRE,
            FECHA_NACIMIENTO = X_FECHA_NACIMIENTO
        WHERE
            ID = V_ID_AUX;
    END IF;
    COMMIT;
    
    SELECT ID
    INTO X_ID_REGISTRO
    FROM PERSONA
    WHERE ID = V_ID_AUX;
    
END SP_UPSERT_USUARIO;
/

-- PARA EJECUTARLO
EXEC SP_UPSER_USUARIO(10, 'SEBASTIAN',TO_DATE('03/05/1989'));

DECLARE
    V_ID NUMBER : :X_ID --5;
BEGIN
    SP_UPSER_USUARIO(V_ID, 'SEBASTIAN',TO_DATE('03/05/1989'));
    DBMS_OUTPUT.PUT_LINE('NUMERO REGISTRO ES: '||V_ID);
    -- NUMERO DE REGISTRO ES: 100
EXCEPTION
    WHEN EXCEPTION IS STRINGNOTVALUEEXCEPTION THEN
        DBMS_OUTPUT.PUT_LINE('NO ES UN STRING LO QUE ME MANDASTE.');
END



BEGIN{

}EXCEPTION EX{
    
}
