
SELECT
    empleado_id,
    nombres || ' ' || apellidos,
    sueldo,
    FN_CALCULASUELDO(sueldo, 15) as PorcentajeSueldo
FROM ej_empleado;

/

CREATE OR REPLACE FUNCTION FN_CALCULASUELDO(
    X_SUELDO EJ_EMPLEADO.SUELDO%TYPE,
    X_PORCENTAJE NUMBER
)
RETURN NUMBER
AS
    V_TOTAL NUMBER;
    V_PORC_INTERNO NUMBER;
BEGIN
    /*
    CREAR UNA FUNCION QUE OBTENGA EL 5% DEL
    SUELDO PARA CASOS DE AFP
    */

    V_PORC_INTERNO := X_PORCENTAJE / 100;
    V_TOTAL := V_PORC_INTERNO * X_SUELDO;
    
    RETURN V_TOTAL;
END FN_CALCULASUELDO;
