DROP TABLE ej_departamento CASCADE CONSTRAINTS;
DROP TABLE ej_rol CASCADE CONSTRAINTS;
DROP TABLE ej_empleado CASCADE CONSTRAINTS;
DROP TABLE ej_manager CASCADE CONSTRAINTS;

DROP SEQUENCE sq_ej_departamento;
DROP SEQUENCE sq_ej_empleado;
DROP SEQUENCE sq_ej_rol;

CREATE TABLE ej_departamento(
    departamento_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_departamento VARCHAR2(100) NOT NULL,
    manager_id NUMBER
);
CREATE TABLE ej_rol(
    rol_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_rol VARCHAR2(50) NOT NULL
);

CREATE TABLE ej_empleado(
    empleado_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombres VARCHAR2(100) NOT NULL,
    apellidos VARCHAR2(100) NOT NULL,
    fechaNac DATE NOT NULL,
    fechaIngreso DATE NOT NULL,
    departamento_id NUMBER NOT NULL,
    manager_ID NUMBER,
    sueldo NUMBER NOT NULL,
    rol_id NUMBER NOT NULL,
    
    CONSTRAINT fk_departamento FOREIGN KEY (Departamento_ID) REFERENCES ej_departamento(departamento_id),
    CONSTRAINT fk_rol_empleado FOREIGN KEY (rol_ID) REFERENCES ej_rol(rol_id)
);

CREATE TABLE ej_manager(
    empleado_id NUMBER PRIMARY KEY,
    departamento_id NUMBER NOT NULL UNIQUE,
    
    CONSTRAINT fk_manager_emp FOREIGN KEY (empleado_id) REFERENCES ej_empleado(empleado_id),
    CONSTRAINT fk_manager_depto FOREIGN KEY (departamento_id) REFERENCES ej_departamento(departamento_id)
);

ALTER TABLE ej_departamento
ADD CONSTRAINT fk_manager_department FOREIGN KEY (manager_ID) REFERENCES ej_empleado(empleado_id);

ALTER TABLE ej_empleado
ADD CONSTRAINT fk_manager FOREIGN KEY (manager_ID) REFERENCES ej_manager(empleado_id);

-- SEQUENCES
CREATE SEQUENCE sq_ej_departamento START WITH 10 INCREMENT BY 10;
CREATE SEQUENCE sq_ej_empleado START WITH 100 INCREMENT BY 13;
CREATE SEQUENCE sq_ej_rol START WITH 5 INCREMENT BY 5;

-- INSERT
INSERT INTO ej_rol(rol_id, nombre_rol) VALUES(sq_ej_rol.nextval, 'sysadmin');
INSERT INTO ej_rol(rol_id, nombre_rol) VALUES(sq_ej_rol.nextval, 'Junior');
INSERT INTO ej_rol(rol_id, nombre_rol) VALUES(sq_ej_rol.nextval, 'Analista');
INSERT INTO ej_rol(rol_id, nombre_rol) VALUES(sq_ej_rol.nextval, 'Programador');
INSERT INTO ej_rol(rol_id, nombre_rol) VALUES(sq_ej_rol.nextval, 'Lider TI');
INSERT INTO ej_rol(rol_id, nombre_rol) VALUES(sq_ej_rol.nextval, 'Subgerente');
INSERT INTO ej_rol(rol_id, nombre_rol) VALUES(sq_ej_rol.nextval, 'Gerente');

INSERT INTO ej_departamento (departamento_id, nombre_departamento, manager_id)
VALUES (sq_ej_departamento.nextval, 'Recursos', null);
INSERT INTO ej_departamento (departamento_id, nombre_departamento, manager_id)
VALUES (sq_ej_departamento.nextval, 'Informatica', null);
INSERT INTO ej_departamento (departamento_id, nombre_departamento, manager_id)
VALUES (sq_ej_departamento.nextval, 'Ventas', null);
INSERT INTO ej_departamento (departamento_id, nombre_departamento, manager_id)
VALUES (sq_ej_departamento.nextval, 'Gerencia', null);

-- EMPLEADOS BASE Y SYSADMIN
INSERT INTO ej_empleado (empleado_id, nombres, apellidos, fechaNac, fechaIngreso, departamento_id,
    manager_id, sueldo, rol_id)
VALUES (sq_ej_empleado.nextval, 'Sebas', 'Contreras', '03/05/1989', SYSDATE, 20, null, 500000, 5);
INSERT INTO ej_empleado (empleado_id, nombres, apellidos, fechaNac, fechaIngreso, departamento_id,
    manager_id, sueldo, rol_id)
VALUES (sq_ej_empleado.nextval, 'Valeria', 'Cerda', '18/09/1980', SYSDATE, 20, null, 500000, 5);
